export const NEWS_REQUESTED = 'NEWS_REQUESTED';
export const NEWS_SUCCESSED = 'NEWS_SUCCESSED';
export const NEWS_FAILED = 'NEWS_FAILED';

export const CHANGE_MODAL_STATE = 'CHANGE_MODAL_STATE';

export const REGISTRATION_REQUESTED = 'REGISTRATION_REQUESTED';
export const REGISTRATION_SUCCESSED = 'REGISTRATION_SUCCESSED';
export const REGISTRATION_FAILED = 'REGISTRATION_FAILED';

export const LOGIN_REQUESTED = 'LOGIN_REQUESTED';
export const LOGIN_SUCCESSED = 'LOGIN_SUCCESSED';

export const LOGOUT = 'LOGOUT';

export const GET_USER_REQUESTED = 'GET_USER_REQUESTED';
export const GET_USER_SUCCESSED = 'GET_USER_SUCCESSED';
export const GET_USER_FAILED = 'GET_USER_FAILED';

export const GET_USER_NEWS_REQUESTED = 'GET_USER_NEWS_REQUESTED';
export const GET_USER_NEWS_SUCCESSED = 'GET_USER_NEWS_SUCCESSED';
export const GET_USER_NEWS_FAILED = 'GET_USER_NEWS_FAILED';

export const ADD_NEWS_REQUESTED = 'ADD_NEWS_REQUESTED';
export const ADD_NEWS_SUCCESSED = 'ADD_NEWS_SUCCESSED';
export const ADD_NEWS_FAILED = 'ADD_NEWS_FAILED';

export const TOGGLE_ADD_NEWS_MODAL = 'TOGGLE_ADD_NEWS_MODAL';
