export const NEWS_REQUESTED = 'NEWS_REQUESTED';
export const NEWS_SUCCESSED = 'NEWS_SUCCESSED';
export const NEWS_FAILED = 'NEWS_FAILED';

export const CHANGE_MODAL_STATE = 'CHANGE_MODAL_STATE';

export const REGISTRATION_REQUESTED = 'REGISTRATION_REQUESTED';
export const REGISTRATION_SUCCESSED = 'REGISTRATION_SUCCESSED';
export const REGISTRATION_FAILED = 'REGISTRATION_FAILED';

export const LOGIN_REQUESTED = 'LOGIN_REQUESTED';
export const LOGIN_SUCCESSED = 'LOGIN_SUCCESSED';

export const LOGOUT = 'LOGOUT';
